subscription_id     = <subscription_id>
location                        = "uaenorth"
use_existing_dns                = false
private_endpoint_name           = "pe-dms-prod-func"
pe_resource_group_name          = "rg-dms-prod"
pdz_resource_group_name         = ["rg-dms-prod"]
subnet_id                       = "/subscriptions/1691759c-bec8-41b8-a5eb-03c57476ffdb/resourceGroups/rg-dms-prod/providers/Microsoft.Network/virtualNetworks/vnet-dms-prod/subnets/snet-dms-db-prod"
private_service_connection_name = "pe-dms-prod-func-aa7c"
manual_connection               = false
sub_resource_id                 = "/subscriptions/1691759c-bec8-41b8-a5eb-03c57476ffdb/resourceGroups/rg-dms-prod/providers/Microsoft.Web/sites/fn-dms-prod"
sub_resource_names              = ["sites"]
azure_private_dns_zone_name     = "privatelink.azurewebsites.net"
custom_network_interface_name   = ""
pdz_name                        = ["privatelink.azurewebsites.net"]
#pdz_counter                    = "0"
#vlink_counter                  = "0"
pdz_link_name                   = ["privatelink-azurewebsites-net"]
virtual_network_id              = ["/subscriptions/1691759c-bec8-41b8-a5eb-03c57476ffdb/resourceGroups/rg-dms-prod/providers/Microsoft.Network/virtualNetworks/vnet-dms-prod"]
vlink_resource_group_name       = ["rg-dms-prod"]
linked_pdz_name                 = ["privatelink.azurewebsites.net"]
private_dns_zone_ids            = ["/subscriptions/1691759c-bec8-41b8-a5eb-03c57476ffdb/resourceGroups/rg-dms-prod/providers/Microsoft.Network/privateDnsZones/privatelink.azurewebsites.net"]
tags = {
  "Application Name" = "DMS"
  "Application Owner" = "Kapil/Rhoderick"
  "ENV" = "PROD"
}
