subscription_id     = <subscription_id>
location                        = "uaenorth"
use_existing_dns                = true
private_endpoint_name           = "pe-dms-nonprod-db"
pe_resource_group_name          = "rg-dms-nonprod"
subnet_id                       = "/subscriptions/1691759c-bec8-41b8-a5eb-03c57476ffdb/resourceGroups/rg-dms-nonprod/providers/Microsoft.Network/virtualNetworks/vnet-dms-nonprod/subnets/snet-dms-db-nonprod"
private_service_connection_name = "pe-dms-nonprod-db"
manual_connection               = false
sub_resource_id                 = "/subscriptions/1691759c-bec8-41b8-a5eb-03c57476ffdb/resourceGroups/rg-dms-nonprod/providers/Microsoft.Sql/servers/sql-dms-nonprod"
sub_resource_names              = ["sqlServer"]
azure_private_dns_zone_name     = "privatelink.database.windows.net"
custom_network_interface_name   = "pe-dms-nonprod-db-nic"
pdz_name                        = ["privatelink.database.windows.net"]
#pdz_counter                    = "0"
#vlink_counter                  = "0"
pdz_link_name                   = ["qagrerbo2lday"]
virtual_network_id              = ["/subscriptions/1691759c-bec8-41b8-a5eb-03c57476ffdb/resourceGroups/rg-dms-nonprod/providers/Microsoft.Network/virtualNetworks/vnet-dms-nonprod"]
vlink_resource_group_name       = ["rg-dms-nonprod"]
linked_pdz_name                 = ["privatelink.database.windows.net"]
private_dns_zone_ids            = ["/subscriptions/1691759c-bec8-41b8-a5eb-03c57476ffdb/resourceGroups/rg-dms-nonprod/providers/Microsoft.Network/privateDnsZones/privatelink.database.windows.net"]
private_dns_zone_group_name     = "rg-dms-nonprod"
pdz_resource_group_name = ["rg-dms-nonprod"]
tags = {
  "Application Name" = "DMS"
  "Application Owner" = "Kapil/Rhoderick"
  "ENV" = "NONPROD"
  "Creator" = "velazadmin"
}
