#### IMPORT EXISTING PRIVATE ENDPOINT ####
subscription_id     = <subscription_id>
location                        = "UAE North"
use_existing_dns                = true
private_endpoint_name           = "pe-psql-wms-staging"
pe_resource_group_name          = "rg-wms-infra-nonprod"
subnet_id                       = "/subscriptions/02b7a2b2-a969-4817-ad92-6f26a5c7afd0/resourceGroups/rg-wms-infra-nonprod/providers/Microsoft.Network/virtualNetworks/vnet-wms-nonprod/subnets/snet-wms-nonprod"
private_service_connection_name = "pe-psql-wms-staging"
manual_connection               = false
pdz_name                        = ["privatelink.postgres.database.azure.com"]
private_dns_zone_group_name     = "default"
private_dns_zone_ids            = ["/subscriptions/02b7a2b2-a969-4817-ad92-6f26a5c7afd0/resourceGroups/rg-wms-infra-nonprod/providers/Microsoft.Network/privateDnsZones/privatelink.postgres.database.azure.com"]
pdz_resource_group_name         = ["rg-wms-infra-nonprod"]
pdz_link_name                   = ["psql-wms-nonprod"]
virtual_network_id              = ["/subscriptions/02b7a2b2-a969-4817-ad92-6f26a5c7afd0/resourceGroups/rg-wms-infra-nonprod/providers/Microsoft.Network/virtualNetworks/vnet-wms-nonprod"]
linked_pdz_name                 = ["privatelink.postgres.database.azure.com"]
vlink_resource_group_name       = ["rg-wms-nonprod"]
sub_resource_id                 = "/subscriptions/02b7a2b2-a969-4817-ad92-6f26a5c7afd0/resourceGroups/rg-wms-nonprod/providers/Microsoft.DBforPostgreSQL/flexibleServers/pg-wms-staging"
sub_resource_names              = ["postgresqlServer"]
azure_private_dns_zone_name     = "privatelink.postgres.database.azure.com"
custom_network_interface_name   = ""
#pdz_counter                     = 0
#vlink_counter                   = 0
