apiVersion: v1
kind: Namespace
metadata:
  name: demo
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  namespace: demo
  labels:
    app: demo-deployment
spec:
  selector:
    matchLabels:
      app: demo-deployment
  template:
    metadata:
      labels:
        app: demo-deployment
    spec:
      containers:
        - name: demo
          image: acrdpwinfra.azurecr.io/http2-demo
          imagePullPolicy: Always
          ports:
            - containerPort: 443
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80;https://+:443
            - name: ASPNETCORE_Kestrel__Certificates__Default__Password
              value: Test1234!
            - name: ASPNETCORE_Kestrel__Certificates__Default__Path
              value: /etc/ssl/private/Cargoes2023.pfx
            - name: ASPNETCORE_ENVIRONMENT
              value: "Release"

---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
  namespace: demo
  # annotations:
  #   service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: demo-deployment
  # type: LoadBalancer
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
      name: https
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-ingress
  namespace: demo
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  # tls:
  # - hosts:
  #   - http2.cargoes.com
  #   secretName: ssl-cargoes-com
  rules:
  - host: http2.cargoes.com
    http:
      paths:
      - backend:
          service:
            name: demo-service
            port:
              number: 443
        path: /
        pathType: Prefix