{
 "title": "CP Dashboard - SP",
 "tags": [ "Skyline" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "d_environment",
    "label": "Environment:",
    "query": {
     "query": "label_values(system_uptime{sp_site_id=~\".+\"},environment)"
    }
   },
   {
    "name": "d_group_id",
    "label": "Maestro ID:",
    "query": {
     "query": "label_values(system_uptime{environment=~\"$d_environment\"}, sp_security_group_id)"
    }
   },
   {
    "name": "d_hostname",
    "label": "Hostname:",
    "query": {
     "query": "label_values(system_uptime{environment=~\"$d_environment\", sp_security_group_id=~\"$d_group_id\"}, host_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "System Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "System Utilization",
   "type": "bargauge",
   "description": "CPU Usage across the entire system",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(SUM(100-system_cpu_utilization{environment=~\"$d_environment\", sp_security_group_id=~\"$d_group_id\", state=\"idle\"})) / (100*count(system_cpu_utilization{environment=~\"$d_environment\", sp_security_group_id=~\"$d_group_id\", state=\"idle\"}))",
     "legendFormat": "CPU Utilization"
    },
    {
     "expr": "sum(system_memory_usage{environment=~\"$d_environment\", sp_security_group_id=~\"$d_group_id\", state=\"used\"}) / ignoring (state) (sum(system_memory_limit{environment=~\"$d_environment\", sp_security_group_id=~\"$d_group_id\"}))",
     "legendFormat": "Memory Utilization"
    }
   ]
  },
  {
   "title": "Cluster state",
   "type": "stat",
   "description": "Maestro cluster state",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (sp_security_group_id) (cluster_xl_mode{environment=~\"$d_environment\", sp_security_group_id=~\"$d_group_id\"})"
    }
   ]
  },
  {
   "title": "Members Info",
   "type": "table",
   "description": "All internal Security Groups Cluster members info",
   "gridPos": { "h": 11, "w": 16, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "max by (environment,sp_security_group_id,host_name) (label_replace(cluster_xl_members_state{environment=~\"$d_environment\", sp_security_group_id=~\"$d_group_id\", id!~\".*local.*\"},\"host_name\",\"$1\",\"name\",\"(.+)\"))"
    },
    {
     "expr": "system_gaia_os_role{environment=~\"$d_environment\", sp_security_group_id=~\"$d_group_id\"}"
    },
    {
     "expr": "system_gaia_os_version{environment=~\"$d_environment\", sp_security_group_id=~\"$d_group_id\"}"
    },
    {
     "expr": "cluster_xl_pnotes{environment=~\"$d_environment\", sp_security_group_id=~\"$d_group_id\"}"
    }
   ]
  },
  {
   "title": "Incoming IO",
   "type": "stat",
   "description": "Network incoming traffic in bits/sec",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (system_network_interface_io_receive_rate{environment=~\"$d_environment\", sp_security_group_id=~\"$d_group_id\", interface!~\"TOTAL|lo\"})"
    }
   ]
  },
  {
   "title": "Outgoing IO",
   "type": "stat",
   "description": "Network incoming traffic in bits/sec",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (system_network_interface_io_transmit_rate{environment=~\"$d_environment\", sp_security_group_id=~\"$d_group_id\", interface!~\"TOTAL|lo\"})"
    }
   ]
  },
  {
   "title": "CPU / Mem / Net / Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Busy by members",
   "type": "timeseries",
   "description": "Average CPU usage of the top members",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (environment,sp_security_group_id,host_name)(100-system_cpu_utilization{environment=~\"$d_environment\", sp_security_group_id=~\"$d_group_id\", host_name=~\"$d_hostname\", state=\"idle\"})",
     "legendFormat": "{{environment}} - {{sp_security_group_id}} - {{host_name}}"
    }
   ]
  },
  {
   "title": "RAM Utilization",
   "type": "timeseries",
   "description": "RAM Utilization",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "system_memory_usage{environment=~\"$d_environment\", sp_security_group_id=~\"$d_group_id\", host_name=~\"$d_hostname\", state=\"used\"} / ignoring (state) (system_memory_limit{environment=~\"$d_environment\", sp_security_group_id=~\"$d_group_id\", host_name=~\"$d_hostname\"}) * 100",
     "legendFormat": "{{environment}} - {{sp_security_group_id}} - {{host_name}}"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "timeseries",
   "description": "Disk Utilization",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "system_filesystem_usage{environment=~\"$d_environment\", sp_security_group_id=~\"$d_group_id\", host_name=~\"$d_hostname\", state=\"used\", mountpoint=\"/\"} / ignoring (state) (system_filesystem_limit{environment=~\"$d_environment\", sp_security_group_id=~\"$d_group_id\", host_name=~\"$d_hostname\", mountpoint=\"/\"}) * 100",
     "legendFormat": "{{environment}} - {{sp_security_group_id}} - {{host_name}}"
    }
   ]
  },
  {
   "title": "SWAP Utilization",
   "type": "timeseries",
   "description": "SWAP Utilization",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "system_paging_usage{environment=~\"$d_environment\", sp_security_group_id=~\"$d_group_id\", host_name=~\"$d_hostname\", state=\"used\"} / ignoring (state) (system_paging_limit{environment=~\"$d_environment\", sp_security_group_id=~\"$d_group_id\", host_name=~\"$d_hostname\"}) * 100",
     "legendFormat": "{{environment}} - {{sp_security_group_id}} - {{host_name}}"
    }
   ]
  },
  {
   "title": "Network IO - Receive",
   "type": "timeseries",
   "description": "Network incoming traffic in bits/sec",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "sum by (environment, sp_security_group_id, host_name) (system_network_interface_io_receive_rate{environment=~\"$d_environment\", sp_security_group_id=~\"$d_group_id\", host_name=~\"$d_hostname\", interface!~\"TOTAL|lo\"})",
     "legendFormat": "{{environment}} - {{sp_security_group_id}} - {{host_name}}"
    }
   ]
  },
  {
   "title": "Network IO - Transmit",
   "type": "timeseries",
   "description": "Network outgoing traffic in bits/sec",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "sum by (environment, sp_security_group_id, host_name) (system_network_interface_io_transmit_rate{environment=~\"$d_environment\", sp_security_group_id=~\"$d_group_id\", host_name=~\"$d_hostname\", interface!~\"TOTAL|lo\"})",
     "legendFormat": "{{environment}} - {{sp_security_group_id}} - {{host_name}}"
    }
   ]
  },
  {
   "title": "Network Packets Drops - Receive",
   "type": "timeseries",
   "description": "Network drops per member",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (environment, sp_security_group_id, host_name) (system_network_dropped_receive{environment=~\"$d_environment\", sp_security_group_id=~\"$d_group_id\", host_name=~\"$d_hostname\", interface!~\"TOTAL|lo\"})",
     "legendFormat": "{{environment}} - {{sp_security_group_id}} - {{host_name}}"
    }
   ]
  },
  {
   "title": "Network Packets Drops - Transmit",
   "type": "timeseries",
   "description": "Network drops per member",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (environment, sp_security_group_id, host_name) (system_network_dropped_transmit{environment=~\"$d_environment\", sp_security_group_id=~\"$d_group_id\", host_name=~\"$d_hostname\", interface!~\"TOTAL|lo\"})",
     "legendFormat": "{{environment}} - {{sp_security_group_id}} - {{host_name}}"
    }
   ]
  },
  {
   "title": "Concurrent Connections",
   "type": "timeseries",
   "description": "Concurrent connections by type",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (environment, sp_security_group_id, host_name) (system_traffic_connections{environment=~\"$d_environment\", sp_security_group_id=~\"$d_group_id\", host_name=~\"$d_hostname\"})",
     "legendFormat": "{{environment}} - {{sp_security_group_id}} - {{host_name}}"
    }
   ]
  },
  {
   "title": "Connection Drops",
   "type": "timeseries",
   "description": "Connection drops by type",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (environment, sp_security_group_id, host_name) (rate(system_traffic_dropped{environment=~\"$d_environment\", sp_security_group_id=~\"$d_group_id\", host_name=~\"$d_hostname\"}[$__rate_interval]))",
     "legendFormat": "{{environment}} - {{sp_security_group_id}} - {{host_name}}"
    }
   ]
  }
 ]
}