subscription_id     = <subscription_id>
name                     = "kvnauprod"
resource_group_name      = "Rgnauprod"
pe_resource_group_name   = "Rg-nau-production"
sku_name                 = "standard"
purge_protection_enabled = false
subnet_id                = ["/subscriptions/ededa550-54e3-4ac7-a6b0-bca51f3c1495/resourceGroups/Rg-nau-production/providers/Microsoft.Network/virtualNetworks/vnet-nau-aks-production/subnets/snet-aks-production"]
virtual_network_id       = ["/subscriptions/ededa550-54e3-4ac7-a6b0-bca51f3c1495/resourceGroups/Rg-nau-production/providers/Microsoft.Network/virtualNetworks/vnet-nau-aks-production"]
# counter=0
# vlink_counter=0
manual_connection               = false
use_existing_dns                = true
use_existing_pe                 = true
private_endpoint_name           = ["pe-kv-nau-production"]
vlink_resource_group_name       = ["Rg-nau-production"]
pdz_resource_group_name         = ["Rg-nau-production"]
private_service_connection_name = ["pe-kv-nau-production"]
private_dns_zone_group_name     = ["default"]
private_dns_zone_ids            = ["/subscriptions/ededa550-54e3-4ac7-a6b0-bca51f3c1495/resourceGroups/Rg-nau-production/providers/Microsoft.Network/privateDnsZones/privatelink.vaultcore.azure.net"]
linked_pdz_name                 = ["privatelink.vaultcore.azure.net"]
pdz_link_name                   = ["d3qxvi5aj6hya"]
pdz_name                        = ["privatelink.vaultcore.azure.net"]
enable_rbac_authorization       = false