subscription_id     = <subscription_id>
name                            = "cnsprod"
resource_group_name             = "rg-cnsprod"
capacity                        = 1
family                          = "P"
sku                             = "Premium"
enable_non_ssl_port             = true
use_existing_pe                 = true
use_existing_dns                = true
private_endpoint_name           = ["privateendpoint-cnspreprod", "privateendpoint-cnsprod"]
pe_resource_group_name          = ["rg-cnsprod", "rg-cnsprod"]
subnet_id                       = ["/subscriptions/5c7ffb4d-2288-4bc0-a920-78bab3f2db58/resourceGroups/cnsnw/providers/Microsoft.Network/virtualNetworks/CNSNetwork/subnets/snet-cnspreprod", "/subscriptions/5c7ffb4d-2288-4bc0-a920-78bab3f2db58/resourceGroups/cnsnw/providers/Microsoft.Network/virtualNetworks/CNSNetwork/subnets/snet-cnsprod"]
private_service_connection_name = ["privateendpoint-cnspreprod", "privateendpoint-cnsprod_f7e00a0f-555a-438c-91d5-c4796430901c"]
manual_connection               = false
pdz_name                        = ["privatelink.redis.cache.windows.net", "privatelink.redis.cache.windows.net"]
private_dns_zone_group_name     = ["default", "default"]
private_dns_zone_ids            = ["/subscriptions/5c7ffb4d-2288-4bc0-a920-78bab3f2db58/resourceGroups/cnsnw/providers/Microsoft.Network/privateDnsZones/privatelink.redis.cache.windows.net", "/subscriptions/5c7ffb4d-2288-4bc0-a920-78bab3f2db58/resourceGroups/cnsnw/providers/Microsoft.Network/privateDnsZones/privatelink.redis.cache.windows.net"]
pdz_resource_group_name         = ["cnsnw", "cnsnw"]
pdz_link_name                   = ["2hdeglrgo2fke", "2hdeglrgo2fke"]
virtual_network_id              = ["/subscriptions/5c7ffb4d-2288-4bc0-a920-78bab3f2db58/resourceGroups/cnsnw/providers/Microsoft.Network/virtualNetworks/CNSNetwork", "/subscriptions/5c7ffb4d-2288-4bc0-a920-78bab3f2db58/resourceGroups/cnsnw/providers/Microsoft.Network/virtualNetworks/CNSNetwork"]
pe_counter                      = 2
pdz_counter                     = 2
vlink_counter                   = 2
linked_pdz_name                 = ["privatelink.redis.cache.windows.net", "privatelink.redis.cache.windows.net"]
vlink_resource_group_name       = ["cnsnw", "cnsnw"]
custom_network_interface_name   = ["", ""]
