subscription_id     = <subscription_id>
name                            = "dpw-foundational-services-staging"
resource_group_name             = "cargoes-staging"
capacity                        = 1
family                          = "P"
sku                             = "Premium"
enable_non_ssl_port             = true
use_existing_pe                 = true
use_existing_dns                = true
private_endpoint_name           = ["dpw-foundational-services-staging"]
pe_resource_group_name          = ["cargoes-staging"]
subnet_id                       = ["/subscriptions/3ddf2459-a8f6-4f71-9fa4-9b3479dbf234/resourceGroups/cargoes-staging/providers/Microsoft.Network/virtualNetworks/cargoes-platform-cluster-staging-vnet/subnets/cargoes-platform-cluster-staging-subnet-2"]
private_service_connection_name = ["dpw-foundational-services-staging_0ceeb574-a5be-4a44-8fdb-02b88e97c013"]
manual_connection               = false
pdz_name                        = ["privatelink.redis.cache.windows.net"]
private_dns_zone_group_name     = ["default"]
private_dns_zone_ids            = ["/subscriptions/3ddf2459-a8f6-4f71-9fa4-9b3479dbf234/resourceGroups/cargoes-staging/providers/Microsoft.Network/privateDnsZones/privatelink.redis.cache.windows.net"]
pdz_resource_group_name         = ["cargoes-staging"]
pdz_link_name                   = ["63575dmga3b2k", "blockchain-link"]
virtual_network_id              = ["/subscriptions/3ddf2459-a8f6-4f71-9fa4-9b3479dbf234/resourceGroups/cargoes-staging/providers/Microsoft.Network/virtualNetworks/cargoes-platform-cluster-staging-vnet", "/subscriptions/dc2a271c-2f36-4ca3-b3b6-79ada4cd5d6b/resourceGroups/rg-BlockchainUAEstaging/providers/Microsoft.Network/virtualNetworks/vnet-BlockchainUAE-staging"]
linked_pdz_name                 = ["privatelink.redis.cache.windows.net", "privatelink.redis.cache.windows.net"]
vlink_resource_group_name       = ["cargoes-staging", "cargoes-staging"]
vlink_counter                   = 2
custom_network_interface_name   = [""]