subscription_id     = <subscription_id>
name                            = "dpw-foundational-services-prod"
resource_group_name             = "cargoes-prod"
capacity                        = 1
family                          = "P"
sku                             = "Premium"
enable_non_ssl_port             = true
use_existing_pe                 = true
use_existing_dns                = true
private_endpoint_name           = ["Foundation-prod-redis-testing", "dpw-foundational-services-prod-redis"]
pe_resource_group_name          = ["cargoes-staging", "cargoes-prod"]
subnet_id                       = ["/subscriptions/3ddf2459-a8f6-4f71-9fa4-9b3479dbf234/resourceGroups/cargoes-staging/providers/Microsoft.Network/virtualNetworks/cargoes-platform-cluster-staging-vnet/subnets/cargoes-platform-cluster-staging-subnet-2", "/subscriptions/368014ab-c35d-4615-a165-842d87aec6f5/resourceGroups/rg-cargoesprod-SharedInfra-prod/providers/Microsoft.Network/virtualNetworks/vnet-cargoessharedapps-prod/subnets/snetakspod"]
private_service_connection_name = ["Foundation-prod-redis-testing", "dpw-foundational-services-prod-redis"]
manual_connection               = false
pdz_name                        = ["privatelink.redis.cache.windows.net", "privatelink.redis.cache.windows.net"]
private_dns_zone_group_name     = ["default", "default"]
private_dns_zone_ids            = ["/subscriptions/3ddf2459-a8f6-4f71-9fa4-9b3479dbf234/resourceGroups/cargoes-staging/providers/Microsoft.Network/privateDnsZones/privatelink.redis.cache.windows.net", "/subscriptions/368014ab-c35d-4615-a165-842d87aec6f5/resourceGroups/rg-cargoesprod-SharedInfra-prod/providers/Microsoft.Network/privateDnsZones/privatelink.redis.cache.windows.net"]
pdz_resource_group_name         = ["cargoes-staging", "rg-cargoesprod-SharedInfra-prod"]
pdz_link_name                   = ["63575dmga3b2k", "blockchain-link", "5ogb7zilwkir2"]
virtual_network_id              = ["/subscriptions/3ddf2459-a8f6-4f71-9fa4-9b3479dbf234/resourceGroups/cargoes-staging/providers/Microsoft.Network/virtualNetworks/cargoes-platform-cluster-staging-vnet", "/subscriptions/dc2a271c-2f36-4ca3-b3b6-79ada4cd5d6b/resourceGroups/rg-BlockchainUAEstaging/providers/Microsoft.Network/virtualNetworks/vnet-BlockchainUAE-staging", "/subscriptions/368014ab-c35d-4615-a165-842d87aec6f5/resourceGroups/rg-cargoesprod-SharedInfra-prod/providers/Microsoft.Network/virtualNetworks/vnet-cargoessharedapps-prod"]
pe_counter                      = 2
pdz_counter                     = 2
vlink_counter                   = 3
linked_pdz_name                 = ["privatelink.redis.cache.windows.net", "privatelink.redis.cache.windows.net", "privatelink.redis.cache.windows.net"]
vlink_resource_group_name       = ["cargoes-staging", "cargoes-staging", "rg-cargoesprod-SharedInfra-prod"]
custom_network_interface_name   = ["Foundation-prod-redis-testing-nic", "dpw-foundational-services-prod-redis-nic"]