subscription_id     = <subscription_id>
name                            = "rc-cargoeslogistics-dev"
resource_group_name             = "rg-cargoesLogisticsplatform-DEV"
capacity                        = 3
family                          = "C"
sku                             = "Basic"
enable_non_ssl_port             = true
use_existing_pe                 = true
use_existing_dns                = true
private_endpoint_name           = ["pvt-cargoelogisticsnewrediscache", "pe-cargoeslogistic-rediscache-dev"]
pe_resource_group_name          = ["cargoes-staging", "rg-cargoesLogisticsplatform-DEV"]
subnet_id                       = ["/subscriptions/3ddf2459-a8f6-4f71-9fa4-9b3479dbf234/resourceGroups/cargoes-staging/providers/Microsoft.Network/virtualNetworks/cargoes-platform-cluster-staging-vnet/subnets/cargoes-platform-cluster-staging-subnet-2", "/subscriptions/a3e25ce2-341c-4f68-b42d-0ec5f349a526/resourceGroups/rg-cargoeslogisticsdev-infra/providers/Microsoft.Network/virtualNetworks/vnet-cargoesLogisitics_dev/subnets/snet-nonprod-dev"]
private_service_connection_name = ["pvt-cargoelogisticsnewrediscache", "pe-cargoeslogistic-rediscache-dev_7b81e5d3-c973-4077-b62c-145f30769027"]
manual_connection               = false
pdz_name                        = ["privatelink.redis.cache.windows.net", "privatelink.redis.cache.windows.net"]
private_dns_zone_group_name     = ["default", "default"]
private_dns_zone_ids            = ["/subscriptions/3ddf2459-a8f6-4f71-9fa4-9b3479dbf234/resourceGroups/cargoes-staging/providers/Microsoft.Network/privateDnsZones/privatelink.redis.cache.windows.net", "/subscriptions/a3e25ce2-341c-4f68-b42d-0ec5f349a526/resourceGroups/rg-cargoeslogisticsdev-infra/providers/Microsoft.Network/privateDnsZones/privatelink.redis.cache.windows.net"]
pdz_resource_group_name         = ["cargoes-staging", "rg-cargoeslogisticsdev-infra"]
pdz_link_name                   = ["63575dmga3b2k", "blockchain-link", "72inbf2kudqw2"]
virtual_network_id              = ["/subscriptions/3ddf2459-a8f6-4f71-9fa4-9b3479dbf234/resourceGroups/cargoes-staging/providers/Microsoft.Network/virtualNetworks/cargoes-platform-cluster-staging-vnet", "/subscriptions/dc2a271c-2f36-4ca3-b3b6-79ada4cd5d6b/resourceGroups/rg-BlockchainUAEstaging/providers/Microsoft.Network/virtualNetworks/vnet-BlockchainUAE-staging", "/subscriptions/a3e25ce2-341c-4f68-b42d-0ec5f349a526/resourceGroups/rg-cargoeslogisticsdev-infra/providers/Microsoft.Network/virtualNetworks/vnet-cargoesLogisitics_dev"]
linked_pdz_name                 = ["privatelink.redis.cache.windows.net", "privatelink.redis.cache.windows.net", "privatelink.redis.cache.windows.net"]
vlink_resource_group_name       = ["cargoes-staging", "cargoes-staging", "rg-cargoeslogisticsdev-infra"]
vlink_counter                   = 3
pe_counter                      = 2
pdz_counter                     = 2
custom_network_interface_name   = ["pvt-cargoelogisticsnewrediscache-nic", ""]