subscription_id     = <subscription_id>
name                            = "rc-trackingserv-dev"
resource_group_name             = "rg-trackingservice-dev"
capacity                        = 1
family                          = "C"
sku                             = "Standard"
enable_non_ssl_port             = true
use_existing_pe                 = true
use_existing_dns                = true
private_endpoint_name           = ["pe-rediscache-dev"]
pe_resource_group_name          = ["rg-trackingservice-dev"]
subnet_id                       = ["/subscriptions/a7831bc0-3c70-4db7-95c4-62d614caf575/resourceGroups/rg-trackingservice-dev-infra/providers/Microsoft.Network/virtualNetworks/Vnet-trackingservice-dev/subnets/snet-nonaks-dev"]
private_service_connection_name = ["pe-rediscache-dev"]
manual_connection               = false
pdz_name                        = ["privatelink.redis.cache.windows.net"]
private_dns_zone_group_name     = ["default"]
private_dns_zone_ids            = ["/subscriptions/a7831bc0-3c70-4db7-95c4-62d614caf575/resourceGroups/rg-trackingservice-dev-infra/providers/Microsoft.Network/privateDnsZones/privatelink.redis.cache.windows.net"]
pdz_resource_group_name         = ["rg-trackingservice-dev-infra"]
pdz_link_name                   = ["63qfku5ydhzni", "trackingservice_prod"]
virtual_network_id              = ["/subscriptions/a7831bc0-3c70-4db7-95c4-62d614caf575/resourceGroups/rg-trackingservice-dev-infra/providers/Microsoft.Network/virtualNetworks/Vnet-trackingservice-dev", "/subscriptions/a7831bc0-3c70-4db7-95c4-62d614caf575/resourceGroups/rg-cargoestrackingservice-infra-prod/providers/Microsoft.Network/virtualNetworks/Vnet-trackingservice-prod"]
linked_pdz_name                 = ["privatelink.redis.cache.windows.net", "privatelink.redis.cache.windows.net"]
vlink_resource_group_name       = ["rg-trackingservice-dev-infra", "rg-trackingservice-dev-infra"]
vlink_counter                   = 2
custom_network_interface_name   = ["pe-rediscache-dev-nic"]