subscription_id     = <subscription_id>
name                            = "redis-cms-prod"
resource_group_name             = "rg-ecommerce-prod"
capacity                        = 2
family                          = "C"
sku                             = "Standard"
enable_non_ssl_port             = false
use_existing_pe                 = true
use_existing_dns                = true
private_endpoint_name           = ["pe-redis-cms-prod", "redis-cms-prod-pri-to-dr"]
pe_resource_group_name          = ["rg-ecommerce-prod", "rg-ecommerce-prod"]
subnet_id                       = ["/subscriptions/039efcb8-56e2-459b-ad3c-68c086e8feb9/resourceGroups/rg-ecommerce-infra-prod/providers/Microsoft.Network/virtualNetworks/vnet-ecommerce-prod/subnets/snet-ecommerce-prod", "/subscriptions/039efcb8-56e2-459b-ad3c-68c086e8feb9/resourceGroups/rg-ecommerce-infra-prod-dr/providers/Microsoft.Network/virtualNetworks/vnet-ecommerce-prod-dr/subnets/snet-ecommerce-prod-dr"]
private_service_connection_name = ["pe-redis-cms-prod_7e1e2b5c-8d61-42d9-8f77-ddd0da0fd03a", "redis-cms-prod-pri-to-dr"]
manual_connection               = false
pdz_name                        = ["privatelink.redis.cache.windows.net"]
private_dns_zone_group_name     = ["default"]
private_dns_zone_ids            = ["/subscriptions/039efcb8-56e2-459b-ad3c-68c086e8feb9/resourceGroups/rg-ecommerce-infra-prod-dr/providers/Microsoft.Network/privateDnsZones/privatelink.redis.cache.windows.net"]
pdz_resource_group_name         = ["rg-ecommerce-infra-prod-dr"]
pdz_link_name                   = ["pkulkhp2aknmk"]
virtual_network_id              = ["/subscriptions/039efcb8-56e2-459b-ad3c-68c086e8feb9/resourceGroups/rg-ecommerce-infra-prod-dr/providers/Microsoft.Network/virtualNetworks/vnet-ecommerce-prod-dr"]
linked_pdz_name                 = ["privatelink.redis.cache.windows.net"]
vlink_resource_group_name       = ["rg-ecommerce-infra-prod-dr"]
pe_counter                      = 2
custom_network_interface_name   = ["", "redis-cms-prod-pri-to-dr-nic"]