subscription_id     = <subscription_id>
aks_cluster_name             = "aks-terraform-test"
aks_resource_group_name      = "rg-infrateam"
keyvault_name                = "kv-infrateam"
keyvault_resource_group_name = "rg-infrateam"
namespace_name               = "azuredevops"
agent_image                  = "acrdpwinfra.azurecr.io/k8s-devops-agent:20230711"
# azp_pool                     = "aks-terraform-test" #name of your agent pool in Azure DevOps config. Should be created beforehand
# azp_url                      = "https://dev.azure.com/dpwhotfsonline"
azp_token_secret = "AZP-TOKEN"