### login to Azure subscription with your AKS cluster:
# az account set --subscription 1691759c-bec8-41b8-a5eb-03c57476ffdb
### enable AKS blob driver:
# az aks update --enable-blob-driver -n aks-infra -g rg-infrateam
### create a kubernetes secret with access key for your Azure storage account:
# kubectl create secret generic azure-secret --from-literal azurestorageaccountname=dpwthanos --from-literal azurestorageaccountkey="your_blob_key" --type=Opaque

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-blob
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  # If set as "Delete" container would be removed after pvc deletion
  storageClassName: azureblob-fuse-premium
  mountOptions:
    - -o allow_other
    - --file-cache-timeout-in-seconds=120
  csi:
    driver: blob.csi.azure.com
    readOnly: false
    # make sure volumeid is unique for every identical storage blob container in the cluster
    # character `#` is reserved for internal use and cannot be used in volumehandle
    volumeHandle: myapplogs
    volumeAttributes:
      containerName: applogs
    nodeStageSecretRef:
      name: azure-secret
      namespace: test

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-blob
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-blob
  storageClassName: azureblob-fuse-premium

---

apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  containers:
    - name: ubuntu
      image: ubuntu
      command: ["sh", "-c", "tail -f /dev/null"]
      securityContext:
        allowPrivilegeEscalation: false
    - name: sidecar
      image: busybox
      command: ["sh", "-c", "tail -f /dev/null"]
      volumeMounts:
        - name: blob01
          mountPath: "/var/applogs"
      securityContext:
        allowPrivilegeEscalation: false
  volumes:
    - name: blob01
      persistentVolumeClaim:
        claimName: pvc-blob