apiVersion: apps/v1
kind: Deployment
metadata:
  name: azdevops-deployment
  namespace: ${namespace}
  labels:
    app: azdevops-agent
spec:
  selector:
    matchLabels:
      app: azdevops-agent
  template:
    metadata:
      labels:
        app: azdevops-agent
    spec:
      containers:
        - name: azdevops-agent
          image: ${agent_image}
          env:
            - name: AZP_URL
              value: ${azp_url}
            - name: AZP_POOL
              value: ${azp_pool}
            - name: AZP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: azdevops
                  key: AZP_TOKEN
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: docker-volume
            - name: secret-store
              mountPath: "/mnt/secret-store"
              readOnly: true
      volumes:
        - name: docker-volume
          hostPath:
            path: /var/run/docker.sock
        - name: secret-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: ${keyvault_name}
