# apiVersion: v1
# kind: Secret
# metadata:
#   name: azdevops
#   namespace: ${namespace}
# data:
#   AZP_POOL: YWtzLWluZnJh
#   AZP_TOKEN: <Personal Access Tokens>
#   AZP_URL: aHR0cHM6Ly9kZXYuYXp1cmUuY29tL2Rwd2hvdGZzb25saW5l

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  namespace: ${namespace}
  name: ${keyvault_name}
spec:
  provider: azure
  secretObjects:
    - secretName: azdevops
      type: Opaque
      data:
        - objectName: ${azp_token_secret}
          key: AZP_TOKEN
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ${userAssignedIdentityID}
    keyvaultName: ${keyvault_name}
    objects: |
      array:
        - |
          objectName: ${azp_token_secret}
          objectType: secret
    tenantId: ${tenant_id}
